package com.roughlyunderscore.enchs.parsers.condition.generic.doubleplayer;

import lombok.ToString;

@ToString
// Aliases
public enum DoublePlayerCondition {
  PLAYER_ONE_PDC_MATCH("PLAYER-ONE-PDC", "PLAYER-ONE-PDC-MATCH", "PLAYER-ONE-PDC-MATCHES", "PLAYER-ONE-PDC-MATCHING", "PLAYER-ONE-PDC-MATCHED"),
  PLAYER_ONE_SNEAKING("PLAYER-ONE-SNEAKING", "PLAYER-ONE-SNEAK", "PLAYER-ONE-SNEAKS", "PLAYER-ONE-SHIFT", "PLAYER-ONE-SHIFTS", "PLAYER-ONE-IS-SNEAKING", "PLAYER-ONE-IS-SNEAK", "PLAYER-ONE-IS-SHIFT", "PLAYER-ONE-IS-SHIFTING"),
  PLAYER_ONE_SPRINTING("PLAYER-ONE-SPRINTING", "PLAYER-ONE-SPRINT", "PLAYER-ONE-SPRINTS", "PLAYER-ONE-IS-SPRINTING", "PLAYER-ONE-IS-SPRINT", "PLAYER-ONE-RUN", "PLAYER-ONE-RUNS", "PLAYER-ONE-IS-RUNNING", "PLAYER-ONE-IS-RUN"),
  PLAYER_ONE_SWIMMING("PLAYER-ONE-SWIMMING", "PLAYER-ONE-SWIM", "PLAYER-ONE-SWIMS", "PLAYER-ONE-IS-SWIMMING", "PLAYER-ONE-IS-SWIM"),
  /**
   * @since 2.2
   */
  PLAYER_ONE_IN_WATER("PLAYER-ONE-IN-WATER"),
  PLAYER_ONE_FLYING("PLAYER-ONE-FLYING", "PLAYER-ONE-FLY", "PLAYER-ONE-FLIES", "PLAYER-ONE-IS-FLYING", "PLAYER-ONE-IS-FLY"),
  PLAYER_ONE_ON_FIRE("PLAYER-ONE-ON-FIRE", "PLAYER-ONE-ON-FIRES", "PLAYER-ONE-IS-ON-FIRE", "PLAYER-ONE-IS-ON-FIRES", "PLAYER-ONE-IS-BURNING", "PLAYER-ONE-IS-BURN", "PLAYER-ONE-IGNITED", "PLAYER-ONE-IS-IGNITED"),
  PLAYER_ONE_ON_HIGHEST_BLOCK("PLAYER-ONE-ON-HIGHEST-BLOCK", "PLAYER-ONE-IS-ON-HIGHEST-BLOCK", "PLAYER-ONE-IS-ON-TOP", "PLAYER-ONE-IS-ON-TOP-BLOCK"),
  PLAYER_ONE_RAIN("PLAYER-ONE-RAIN", "PLAYER-ONE-RAINS", "PLAYER-ONE-IS-RAINING", "PLAYER-ONE-DOWNFALL", "PLAYER-ONE-IS-DOWNFALL"),
  PLAYER_ONE_CLEAR("PLAYER-ONE-CLEAR", "PLAYER-ONE-IS-CLEAR", "PLAYER-ONE-IS-NOT-RAINING", "PLAYER-ONE-IS-NOT-DOWNFALL"),
  PLAYER_ONE_THUNDER("PLAYER-ONE-THUNDER", "PLAYER-ONE-THUNDERS", "PLAYER-ONE-IS-THUNDERING", "PLAYER-ONE-IS-THUNDER", "PLAYER-ONE-IS-THUNDER-STORM", "PLAYER-ONE-IS-THUNDER-STORMING"),
  PLAYER_ONE_DAY("PLAYER-ONE-DAY", "PLAYER-ONE-IS-DAY", "PLAYER-ONE-IS-DAYTIME", "PLAYER-ONE-IS-DAY-TIME"),
  PLAYER_ONE_NIGHT("PLAYER-ONE-NIGHT", "PLAYER-ONE-IS-NIGHT", "PLAYER-ONE-IS-NIGHTTIME", "PLAYER-ONE-IS-NIGHT-TIME"),
  PLAYER_ONE_OVERWORLD("PLAYER-ONE-OVERWORLD", "PLAYER-ONE-IS-OVERWORLD", "PLAYER-ONE-IS-OVER-WORLD", "PLAYER-ONE-IS-OVERWORLD-LEVEL", "PLAYER-ONE-IS-OVER-WORLD-LEVEL"),
  PLAYER_ONE_NETHER("PLAYER-ONE-NETHER", "PLAYER-ONE-IS-NETHER", "PLAYER-ONE-IS-NETHER-LEVEL", "PLAYER-ONE-IS-NETHER-WORLD", "PLAYER-ONE-IS-NETHER-WORLD-LEVEL", "PLAYER-ONE-HELL", "PLAYER-ONE-IS-HELL", "PLAYER-ONE-IS-HELL-LEVEL", "PLAYER-ONE-IS-HELL-WORLD", "PLAYER-ONE-IS-HELL-WORLD-LEVEL"),
  PLAYER_ONE_END("PLAYER-ONE-END", "PLAYER-ONE-IS-END", "PLAYER-ONE-IS-END-LEVEL", "PLAYER-ONE-IS-END-WORLD", "PLAYER-ONE-IS-END-WORLD-LEVEL", "PLAYER-ONE-THE-END", "PLAYER-ONE-IS-THE-END", "PLAYER-ONE-IS-THE-END-LEVEL", "PLAYER-ONE-IS-THE-END-WORLD", "PLAYER-ONE-IS-THE-END-WORLD-LEVEL"),
  PLAYER_ONE_OP("PLAYER-ONE-OP", "PLAYER-ONE-IS-OP", "PLAYER-ONE-IS-OPERATOR", "PLAYER-ONE-OPERATOR", "PLAYER-OP", "PLAYER-IS-OP", "PLAYER-IS-OPERATOR", "PLAYER-OPERATOR"),
  PLAYER_ONE_BLOCKING("PLAYER-ONE-BLOCKING", "PLAYER-ONE-IS-BLOCKING", "PLAYER-ONE-BLOCKING-IS", "PLAYER-ONE-BLOCK", "PLAYER-ONE-IS-BLOCK", "PLAYER-ONE-BLOCK-IS"),

  PLAYER_ONE_HEALTH("PLAYER-ONE-HEALTH", "PLAYER-ONE-IS-HEALTH", "PLAYER-ONE-HEALTH-IS"),
  PLAYER_ONE_FOOD("PLAYER-ONE-FOOD", "PLAYER-ONE-IS-FOOD", "PLAYER-ONE-FOOD-IS"),
  PLAYER_ONE_AIR("PLAYER-ONE-AIR", "PLAYER-ONE-IS-AIR", "PLAYER-ONE-AIR-IS"),
  PLAYER_ONE_GODMODE("PLAYER-ONE-GODMODE", "PLAYER-ONE-IS-GODMODE", "PLAYER-ONE-GODMODE-IS", "PLAYER-ONE-GOD", "PLAYER-ONE-IS-GOD", "PLAYER-ONE-GOD-IS"),

  PLAYER_TWO_PDC_MATCH("PLAYER-TWO-PDC", "PLAYER-TWO-PDC-MATCH", "PLAYER-TWO-PDC-MATCHES", "PLAYER-TWO-PDC-MATCHING", "PLAYER-TWO-PDC-MATCHED"),
  PLAYER_TWO_SNEAKING("PLAYER-TWO-SNEAKING", "PLAYER-TWO-SNEAK", "PLAYER-TWO-SNEAKS", "PLAYER-TWO-SHIFT", "PLAYER-TWO-SHIFTS", "PLAYER-TWO-IS-SNEAKING", "PLAYER-TWO-IS-SNEAK", "PLAYER-TWO-IS-SHIFT", "PLAYER-TWO-IS-SHIFTING"),
  PLAYER_TWO_SPRINTING("PLAYER-TWO-SPRINTING", "PLAYER-TWO-SPRINT", "PLAYER-TWO-SPRINTS", "PLAYER-TWO-IS-SPRINTING", "PLAYER-TWO-IS-SPRINT", "PLAYER-TWO-RUN", "PLAYER-TWO-RUNS", "PLAYER-TWO-IS-RUNNING", "PLAYER-TWO-IS-RUN"),
  PLAYER_TWO_SWIMMING("PLAYER-TWO-SWIMMING", "PLAYER-TWO-SWIM", "PLAYER-TWO-SWIMS", "PLAYER-TWO-IS-SWIMMING", "PLAYER-TWO-IS-SWIM"),
  /**
   * @since 2.2
   */
  PLAYER_TWO_IN_WATER("PLAYER-TWO-IN-WATER"),
  PLAYER_TWO_FLYING("PLAYER-TWO-FLYING", "PLAYER-TWO-FLY", "PLAYER-TWO-FLIES", "PLAYER-TWO-IS-FLYING", "PLAYER-TWO-IS-FLY"),
  PLAYER_TWO_ON_FIRE("PLAYER-TWO-ON-FIRE", "PLAYER-TWO-ON-FIRES", "PLAYER-TWO-IS-ON-FIRE", "PLAYER-TWO-IS-ON-FIRES", "PLAYER-TWO-IS-BURNING", "PLAYER-TWO-IS-BURN", "PLAYER-TWO-IGNITED", "PLAYER-TWO-IS-IGNITED"),
  PLAYER_TWO_ON_HIGHEST_BLOCK("PLAYER-TWO-ON-HIGHEST-BLOCK", "PLAYER-TWO-IS-ON-HIGHEST-BLOCK", "PLAYER-TWO-IS-ON-TOP", "PLAYER-TWO-IS-ON-TOP-BLOCK"),
  PLAYER_TWO_RAIN("PLAYER-TWO-RAIN", "PLAYER-TWO-RAINS", "PLAYER-TWO-IS-RAINING", "PLAYER-TWO-DOWNFALL", "PLAYER-TWO-IS-DOWNFALL"),
  PLAYER_TWO_CLEAR("PLAYER-TWO-CLEAR", "PLAYER-TWO-IS-CLEAR", "PLAYER-TWO-IS-NOT-RAINING", "PLAYER-TWO-IS-NOT-DOWNFALL"),
  PLAYER_TWO_THUNDER("PLAYER-TWO-THUNDER", "PLAYER-TWO-THUNDERS", "PLAYER-TWO-IS-THUNDERING", "PLAYER-TWO-IS-THUNDER", "PLAYER-TWO-IS-THUNDER-STORM", "PLAYER-TWO-IS-THUNDER-STORMING"),
  PLAYER_TWO_DAY("PLAYER-TWO-DAY", "PLAYER-TWO-IS-DAY", "PLAYER-TWO-IS-DAYTIME", "PLAYER-TWO-IS-DAY-TIME"),
  PLAYER_TWO_NIGHT("PLAYER-TWO-NIGHT", "PLAYER-TWO-IS-NIGHT", "PLAYER-TWO-IS-NIGHTTIME", "PLAYER-TWO-IS-NIGHT-TIME"),
  PLAYER_TWO_OVERWORLD("PLAYER-TWO-OVERWORLD", "PLAYER-TWO-IS-OVERWORLD", "PLAYER-TWO-IS-OVER-WORLD", "PLAYER-TWO-IS-OVERWORLD-LEVEL", "PLAYER-TWO-IS-OVER-WORLD-LEVEL"),
  PLAYER_TWO_NETHER("PLAYER-TWO-NETHER", "PLAYER-TWO-IS-NETHER", "PLAYER-TWO-IS-NETHER-LEVEL", "PLAYER-TWO-IS-NETHER-WORLD", "PLAYER-TWO-IS-NETHER-WORLD-LEVEL", "PLAYER-TWO-HELL", "PLAYER-TWO-IS-HELL", "PLAYER-TWO-IS-HELL-LEVEL", "PLAYER-TWO-IS-HELL-WORLD", "PLAYER-TWO-IS-HELL-WORLD-LEVEL"),
  PLAYER_TWO_END("PLAYER-TWO-END", "PLAYER-TWO-IS-END", "PLAYER-TWO-IS-END-LEVEL", "PLAYER-TWO-IS-END-WORLD", "PLAYER-TWO-IS-END-WORLD-LEVEL", "PLAYER-TWO-THE-END", "PLAYER-TWO-IS-THE-END", "PLAYER-TWO-IS-THE-END-LEVEL", "PLAYER-TWO-IS-THE-END-WORLD", "PLAYER-TWO-IS-THE-END-WORLD-LEVEL"),
  PLAYER_TWO_OP("PLAYER-TWO-OP", "PLAYER-TWO-IS-OP", "PLAYER-TWO-IS-OPERATOR", "PLAYER-TWO-OPERATOR"),
  PLAYER_TWO_BLOCKING("PLAYER-TWO-BLOCKING", "PLAYER-TWO-IS-BLOCKING", "PLAYER-TWO-BLOCKING-IS", "PLAYER-TWO-BLOCK", "PLAYER-TWO-IS-BLOCK", "PLAYER-TWO-BLOCK-IS"),

  PLAYER_TWO_HEALTH("PLAYER-TWO-HEALTH", "PLAYER-TWO-IS-HEALTH", "PLAYER-TWO-HEALTH-IS"),
  PLAYER_TWO_FOOD("PLAYER-TWO-FOOD", "PLAYER-TWO-IS-FOOD", "PLAYER-TWO-FOOD-IS"),
  PLAYER_TWO_AIR("PLAYER-TWO-AIR", "PLAYER-TWO-IS-AIR", "PLAYER-TWO-AIR-IS"),
  PLAYER_TWO_GODMODE("PLAYER-TWO-GODMODE", "PLAYER-TWO-IS-GODMODE", "PLAYER-TWO-GODMODE-IS", "PLAYER-TWO-GOD", "PLAYER-TWO-IS-GOD", "PLAYER-TWO-GOD-IS");

  private final String[] name;

  DoublePlayerCondition(String... name) {
    String[] names = new String[name.length];
    for (int i = 0; i < name.length; i++) names[i] = name[i].toUpperCase();

    this.name = names;
  }

  DoublePlayerCondition() {
    this.name = new String[] {this.name()};
  }


  public boolean matches(final String arg) {
    for (String name : name) if (name.equals(arg.toUpperCase())) return true;
    return false;
  }

  public static DoublePlayerCondition lookup(final String arg) {
    for (DoublePlayerCondition condition : values()) if (condition.matches(arg)) return condition;
    return null;
  }
}
